export { Client } from './client.js'
export { type Connector, type ConnectorData } from './connectors/base.js'
export { InjectedConnector } from './connectors/injected.js'
export { EthersQueryProvider, useEthersQuery, type EthersQueryProviderProps } from './context.js'
export { useAccount, type AccountData } from './hooks/useAccount.js'
export { useProvider } from './hooks/useProvider.js'
export { useSigner } from './hooks/useSigner.js'
export { useSignMessage } from './hooks/useSignMessage.js'
export { useSmartContract } from './hooks/useSmartContract.js'

